### ISSUE TITLE
Support multiple versions of documentation on GitHub Pages

### ISSUE THREAD

**Issue by ns-rse** [Mesnage-Org/pgfinder#143] opened 2023-04-18 14:00 UTC
Use the [sphinxcontrib-versioning](https://github.com/sphinx-contrib/sphinxcontrib-versioning) extension to support multiple versions of documentation hosted on GitHub Pages.

**Comment by ns-rse** [comment] 2023-04-19 06:24
[`sphinxcontrib-versioning`](https://github.com/sphinx-contrib/sphinxcontrib-versioning/) doesn't work with Sphinx > 2.0 (see [issue 77](https://github.com/sphinx-contrib/sphinxcontrib-versioning/issues/77)) which has languished for some time.

An alternative is to use [sphinx-multiversion](https://holzhaus.github.io/sphinx-multiversion/master/index.html).

**Comment by TheLostLambda** [comment] 2023-09-09 10:25
Is this another issue that can now be closed?

**Comment by TheLostLambda** [comment] 2023-09-09 13:52
Closing as a potential duplicate of #228

**Closed by TheLostLambda** 2023-09-09 13:52 UTC
Labels: documentation, CI/CD
