### ISSUE TITLE
Delete columns in the matching output (thought it had been done with #65 but it has not!) 

### ISSUE THREAD

**Issue by smesnage** [Mesnage-Org/pgfinder#112] opened 2022-06-30 11:54 UTC
3 columns to delete (see attached) 

feature 
corrMax 
maxIsotopeCount

[delete_columns.pdf](https://github.com/Mesnage-Org/pgfinder/files/9019510/delete_columns.pdf)

**Comment by smesnage** [comment] 2022-06-30 17:19
See #65?

**Comment by ns-rse** [comment] 2022-07-01 09:02
Strange, #71 was merged, it may have been caused by someone (like me) having been working on from an earlier branch.

Would be worth ensuring that these are not included in the changes made in #104

**Closed** 2022-07-28 15:14 UTC
